service: import
app: tracklist-editor
org: elliotchance
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  apple-music:
    handler: apple-music.import
    events:
      - http:
          path: /apple-music
          method: GET
          cors: true
          request:
            parameters:
              querystrings:
                url: true
  
  spotify:
    handler: spotify.import
    events:
      - http:
          path: /spotify
          method: GET
          cors: true
          request:
            parameters:
              querystrings:
                url: true
